export const welcomeLoginText = "Seja bem-vindo!"
export const subTitleLoginText = "Nós sabemos a importância de estar sempre de barriga cheia e o quanto isso pode ajudar no seu dia."
export const loginButtonText = "Entrar"
export const saveButtonText = "Salvar"
export const emailText = "E-mail"
export const senhaText = "Senha"
export const insertEmailText = "Insira o seu e-mail aqui"
export const insertSenhaText = "Insira a sua senha aqui"